#!/bin/sh
. /lib/trlimit/common.sh

HELP_TEXT="You can change these settings via SSH.
The relevant files are:
/etc/config/trlimit
TBD
This mail was autogenerated by the program trlimit."

TRAFFIC_LIMIT_PRESET="A traffic limit is now in effect:
Upload max.\t%s kbit/s
Download max.\t%s kbit/s
for the rest of the %s
on the interface $interface/$interfaceNick."

FULL_TEXT_PRESET="Dear administrator of %s,
The given traffic limit of %s KB on the connection %s/%s for this %s has been surpassed at this time:
%s
%s
%s"

checkIfMailAlreadySent() {
	if [ -f "$MAIL_SENT_FOLDER$interfaceNick" ]
	then
		echo 1
	else
		echo 0
	fi
	return 0
}
setMailAlreadySent() {
	local interfaceNick="$1"
	touch "$MAIL_SENT_FOLDER$interfaceNick"
}
resetMailAlreadySent() {
	local interfaceNick="$1"
	rm "$MAIL_SENT_FOLDER$interfaceNick"
}
resetAllMailAlreadySent() {
	rm "$MAIL_SENT_FOLDER*"
}
sendMailForInterfaceLimit() {
	local interfaceLimit="$1"
	local interface
	local interfaceNick
	local enabled
	local upload_limit
	local download_limit
	local threshold
	local sourcename
	local mailaddress
	
	config_load "$CONFIG_FILE"
	
	config_get interface "$interfaceLimit" "interface"
	config_get interfaceNick "$interfaceLimit" "interfaceNick"
	config_get_bool enabled "$interfaceLimit" "enabled"
	config_get upload_limit "$interfaceLimit" "upload_limit"
	config_get download_limit "$interfaceLimit" "download_limit"
	config_get threshold "$interfaceLimit" "threshold"
	config_get sourcename service "sourcename"
	config_get mailaddress service "mailaddress"
	
	local mailtext
	mailtext="$(generateMessage "$sourcename" "$interface" "$interfaceNick" month "$upload_limit" "$download_limit" "$enabled")"
	
	sendGeneratedMail "$mailaddress" "TrafficAlert on $sourceName $interface/$interfaceNick" "$mailtext"
	log notice "Sent mail to $mailaddress about $interface/$interfaceNick."
	setMailAlreadySent "$interfaceNick"
}
generateTrafficLimitText() {
	local interface=$1
	local interfaceNick=$2
	local interval=$3
	local upload=$4
	local download=$5
	
	printf "$TRAFFIC_LIMIT_PRESET" "$upload" "$download" "$interval"
}
generateMessage() {
	local sourceName="$1"
	local threshold="$2"
	local interface="$2"
	local interfaceNick="$3"
	local interval="$4"
	local upload="$5"
	local download="$6"
	local trafficLimitEnabled="$7"
	local trafficLimitText
	if [ "$trafficLimitEnabled" != 0 ]
	then
		trafficLimitText=$(generateTrafficLimitText "$interface" "$interfaceNick" "$interval" "$upload" "$download")
	else
		trafficLimitText=""
	fi
	local timestamp
	timestamp=$(date -u)
	printf  "$FULL_TEXT_PRESET" "$sourceName" "$threshold" "$interface" "$interfaceNick" "$interval" "$timestamp" "$trafficLimitText" "$HELP_TEXT"
}



sendGeneratedMail() {
	local recipient=$1
	local subject=$2
	local text=$3
	local mail="To: $recipient
Subject: $subject

$text"
	printf "$mail" > temp.txt
	sendmail -t < temp.txt
	rm temp.txt
}
