#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

. /lib/functions.sh
. /lib/trlimit/common.sh

USE_PROCD=1
START=99
STOP=01


cleanUpQosConfig() {
	local wasOverwritten
	wasOverwritten=$(uci -q get qos."$OVERWRITTEN_STR")
	local error=$?
	if [ $error = 0 ]
	then
		if [ -f "$QOS_BACKUP_FILE" ]		
			then
				log notice "Trlimit is reseting the qos config."
				stopQOS
				cp "$QOS_BACKUP_FILE" "$QOS_CONFIG_FOLDER" #backup -> qos
				startQOS
			else
				log error "Trlimit tried to restore the qos config, but the backupfile does not exist. Exiting.\n"
				exit 1
		fi
	fi
}
start_service() {
	procd_open_instance
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param command sh /usr/sbin/trlimit
	procd_set_param file "$CONFIG_FILE_FULL"
	procd_close_instance
	log notice "trlimit started"
}

stop_service() {
	cleanUpQosConfig

	log notice "trlimit stopped"
}

